require 'support/factories/branch'
require 'support/factories/build'
require 'support/factories/commit'
require 'support/factories/cron'
require 'support/factories/job'
require 'support/factories/log'
require 'support/factories/organization'
require 'support/factories/pull_request'
require 'support/factories/repository'
require 'support/factories/request'
require 'support/factories/ssl_key'
require 'support/factories/stage'
require 'support/factories/tag'
require 'support/factories/user'

FactoryBot.define do
  factory :email
  factory :token
  factory :star
  factory :membership
  factory :user_beta_feature
  factory :permission
  factory :trial
  factory :trial_allowance
  factory :broadcast
  factory :subscription
  factory :invoice
  factory :owner_group
  factory :message
  factory :abuse
  factory :annotation
  factory :queueable_job
end